### ISSUE TITLE
angular2怎么输出html？

### ISSUE THREAD

**Issue by jakechan2012** [lewis617/angular2-tutorial#2]
先星星支持，我现在有这样一个场景，文章是用markdown写的，使用marked在前端转成html显示。angular1的时候是用$sce.trustAsHtml来实现的，但是目前angular2的资料很少，官网的quick start/api英文文档看起来很吃力。
求博主帮助，感激。

**Comment by lewis617** [comment]
https://github.com/kittencup/angular2-ama-cn/issues/146

This maybe helpful.@jakechan2012

**Comment by jakechan2012** [comment]
@lewis617 thank you so much, it works
