### ISSUE TITLE
How does the deploy on github pages work?

### ISSUE THREAD

**Issue by MoYummy** [lewis617/angular2-tutorial#4]
I am curious about deploy of ng2 app in this repo. It just uploads source code and github pages automatically sets up the site. It looks like magic to me. :)

I have two sets of puzzles:
1. Why does this work? What is the mechanism? Is there any doc for this?
2. Is this a practical way to deploy a lite version of ng2 app? If so, how can I test like ```npm start``` to preview my site locally before submitting a commit? And also how can I set up and run test framework?

It would be much appreciated if you could resolve my puzzles. Thanks in advance. :)

**Comment by lewis617** [comment]
1.[Github Pages](https://pages.github.com/) provides the service, so I can deploy them.
2.you can use the  [angular-cli](https://github.com/angular/angular-cli) to deploy your ng2 app. [angular2-daily-task](https://github.com/lewis617/angular2-daily-task) is using angular-cli. That's great!

This project (angular2-tutorial) does not use the angular-cli, I use the system.js to import the lib and run in browser.

**Comment by MoYummy** [comment]
Thanks for the clarification.
